events { worker_connections 1024; }
http {
    server {
        listen 80;
        server_name dezhur-app.ru;
        return 301 https://$host$request_uri; # Редирект на HTTPS
    }

    server {
        listen 443 ssl;
        server_name dezhur-app.ru;

        ssl_certificate /etc/letsencrypt/live/dezhur-app.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dezhur-app.ru/privkey.pem;

        location / {
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}