events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Разрешает проброс заголовка X-TG-Data (превращает его в $http_x_tg_data)
    underscores_in_headers on;

    limit_req_zone $binary_remote_addr zone=global_limit:10m rate=5r/s;
    limit_req_zone $binary_remote_addr zone=strict_limit:10m rate=1r/s;

    # HTTP на HTTPS редирект
    server {
        listen 80;
        server_name dezhur-app.ru;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name dezhur-app.ru;

        ssl_certificate /etc/letsencrypt/live/dezhur-app.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dezhur-app.ru/privkey.pem;

        root /usr/share/nginx/html;
        index index.html;

        # Блок API: ловит всё, что начинается на /api (включая /api/v1/)
        location /api/ {
            # 1. Исправляем CORS для dev-режима (обработка OPTIONS)
#             if ($request_method = 'OPTIONS') {
#                 add_header 'Access-Control-Allow-Origin' '*' always;
#                 add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
#                 add_header 'Access-Control-Allow-Headers' 'X-TG-Data, Content-Type, Authorization' always;
#                 add_header 'Access-Control-Max-Age' 1728000;
#                 add_header 'Content-Type' 'text/plain; charset=utf-8';
#                 add_header 'Content-Length' 0;
#                 return 204;
#             }

            # 2. Проксирование на бэкенд
            limit_req zone=global_limit burst=10 nodelay;т
            proxy_pass http://api:8000;

            # 3. Проброс кастомного заголовка Телеграма
            proxy_set_header X-TG-Data $http_x_tg_data;

            # 4. Стандартные прокси-заголовки
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 5. CORS заголовки для обычных запросов
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Headers' 'X-TG-Data, Content-Type, Authorization' always;
        }

        # 2. ФРОНТЕНД - статика и роутинг
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        # Кеширование статики
        location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2)$ {
            root /usr/share/nginx/html;
            expires 7d;
            add_header Cache-Control "public, no-transform";
        }
    }
}