"""add_student_id_to_invites

Revision ID: 3d3a3e9e2636
Revises: 51f966d38354
Create Date: 2026-01-20 12:08:43.824592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3a3e9e2636'
down_revision: Union[str, Sequence[str], None] = '51f966d38354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # Обертываем изменения в batch_alter_table
  with op.batch_alter_table('invite_links', schema=None) as batch_op:
    # Добавляем колонку
    batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
    # Создаем внешний ключ
    batch_op.create_foreign_key(
      'fk_invite_student',  # Имя ключа (можно любое уникальное)
      'students',  # К какой таблице цепляемся
      ['student_id'],  # Наша колонка
      ['id']  # Колонка в целевой таблице
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite_links', type_='foreignkey')
    op.drop_column('invite_links', 'student_id')
    # ### end Alembic commands ###
