"""add_duty_exchange_model

Revision ID: 06cad72c697d
Revises: 2c6644622249
Create Date: 2026-05-28 21:54:30.115660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cad72c697d'
down_revision: Union[str, Sequence[str], None] = '2c6644622249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('initiator_duty_id', sa.Integer(), nullable=False),
    sa.Column('suggested_id', sa.Integer(), nullable=False),
    sa.Column('suggested_duty_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='exchangestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiator_duty_id'], ['duty_schedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiator_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_duty_id'], ['duty_schedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('curators', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'curators', 'groups', ['group_id'], ['id'])
    op.drop_constraint(op.f('groups_curator_id_fkey'), 'groups', type_='foreignkey')
    op.drop_column('groups', 'curator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('curator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('groups_curator_id_fkey'), 'groups', 'curators', ['curator_id'], ['id'], onupdate='SET NULL')
    op.drop_constraint(None, 'curators', type_='foreignkey')
    op.drop_column('curators', 'group_id')
    op.drop_table('duty_exchanges')
    # ### end Alembic commands ###
