"""add_curator_id_to_groups

Revision ID: 42b9d32fac64
Revises: 2cf136b666b0
Create Date: 2026-02-01 22:54:19.676264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b9d32fac64'
down_revision: Union[str, Sequence[str], None] = '2cf136b666b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('curator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'curators', ['curator_id'], ['id'], onupdate='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'curator_id')
    # ### end Alembic commands ###
