"""empty message

Revision ID: 9f8363b5fd3b
Revises: dfae6d2e1f8c
Create Date: 2026-02-02 01:15:22.063368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8363b5fd3b'
down_revision: Union[str, Sequence[str], None] = 'dfae6d2e1f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duty_settings', sa.Column('person_per_day', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duty_settings', 'person_per_day')
    # ### end Alembic commands ###
