"""fix_missing_duty_table

Revision ID: dfae6d2e1f8c
Revises: 068c4c77e779
Create Date: 2026-02-02 00:32:30.119552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfae6d2e1f8c'
down_revision: Union[str, Sequence[str], None] = '068c4c77e779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
